server: 
  port: 7000
  servlet:
    context-path: /market
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
    
mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  type-aliases-package: com.yzh.market.entity;com.yzh.market.vo;
  
logging:
  level:
     com.yzh.market.mapper: debug
     

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/second_market?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
prop:
  upload-folder: classpath:static/image
# mybatis-generator:generate